# Generated by Django 3.2.4 on 2021-07-27 06:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userauth', '__first__'),
        ('distributor', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(auto_now_add=True, null=True)),
                ('order_time', models.TimeField(auto_now_add=True, null=True)),
                ('payable_amount', models.IntegerField(default=1500, null=True)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('gas_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='name_of_gas', to='distributor.addgas')),
                ('store_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_name', to='userauth.distributor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_details', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order',
            },
        ),
        migrations.CreateModel(
            name='FeedbackComplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='feedback', max_length=50)),
                ('subject', models.CharField(max_length=50, null=True)),
                ('message', models.CharField(max_length=1024, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_complaint', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
